#!/bin/bash
res=""
buf=""
while IFS="" read str
do
    if [ -z "${str##* *}" ]
    then
        key="${str%% *}"
        val="${str#* }"
    else
        key="${str}"
        val=""
    fi
    if [ -z "${key}" ]
    then
        buf="${buf}"$'\n'"${val}"
    elif [ -n "${buf}" ]
    then
        res="$(echo -n "${buf}" | $1 "${res}")"
        buf="${val}"
    fi
done
if [ -n "${buf}" ]
    res="$(echo -n "${buf}" | $1 "${res}")"
    buf="${val}"
fi
echo -n "${res}"
