#!/bin/bash
res=""
buf=""
key=""
while IFS="" read str
do
    if [ -z "${str##* *}" ]
    then
        newkey="${str%% *}"
        val="${str#* }"
    else
        newkey="${str}"
        val=""
    fi
    if [ -z "${newkey}" ]
    then
        buf="${buf}"$'\n'"${val}"
    else
        if [ -n "${buf}" ]
        then
            eval $1
        fi
        key="${newkey}"
        buf="${val}"
    fi
done
if [ -n "${buf}" ]
then
    eval $1
fi
echo -n "${res}"
